jobs:
- job:
  displayName: vs2017-win2016
  pool:
    vmImage: 'vs2017-win2016'

  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: 'Add conda to PATH'
  
  - script: |
      call activate
      conda config --set always_yes yes --set changeps1 no
      conda config --append channels conda-forge
      conda update conda
      conda update -q --all
    displayName: 'Install Anaconda Packages'
  
  - powershell: (get-content test-environment.yaml) | %{$_ -replace "\$\{PYTHON\}","$(python.version)"} | set-content test-environment.yaml
    displayName: 'Set appropriate Python version in environment file'

  - script: |
      conda env create --quiet --file test-environment.yaml
      call activate py$(python.version)
      conda info -a
    displayName: 'Create Anaconda environment'
  
  - powershell: Write-Host "Packages in py3.x Environment:"
    displayName: 'List packages'
    
  - script: conda list -n py$(python.version)
    displayName: 'List package in environment'

  - script: |
      pip install pytest-cov pytest-azurepipelines
      pytest -v --cov=./ --cov-report html
    displayName: 'test with pytest'
